LLPATH=/Users/martin/Developer/tum/ss21/bsc/llvm-project/build/bin

XCOMPILE_X86_FLAGS=--target=x86_64-linux-gnu --sysroot=/Users/martin/Developer/tum/ss21/bsc/benchmarks/x86-sysroot -fuse-ld=${LLPATH}/ld.lld
XCOMPILE_ARM_FLAGS=--target=aarch64-linux-gnu --sysroot=/Users/martin/Developer/tum/ss21/bsc/benchmarks/aarch64-sysroot -fuse-ld=${LLPATH}/ld.lld

MCTOLL_INCLUDE=${INCLUDE_DIR}/stddev.h,${INCLUDE_DIR}/stdio.h,${INCLUDE_DIR}/stdlib.h,${INCLUDE_DIR}/string.h,${INCLUDE_DIR}/strings.h,${INCLUDE_DIR}/pthread.h,${INCLUDE_DIR}/unistd.h,${INCLUDE_DIR}/time.h,${INCLUDE_DIR}/stdint.h,${INCLUDE_DIR}/x86_64-linux-gnu/sys/stat.h,${INCLUDE_DIR}/fcntl.h,${INCLUDE_DIR}/x86_64-linux-gnu/sys/mman.h,${INCLUDE_DIR}/sched.h,${INCLUDE_DIR}/ctype.h,${INCLUDE_DIR}/math.h,${INCLUDE_DIR}/arpa/inet.h,/Users/martin/Developer/tum/ss21/bsc/benchmarks/missing_functions.h

export CC=${LLPATH}/clang ${XCOMPILE_X86_FLAGS}
export CC_ARM=${LLPATH}/clang ${XCOMPILE_ARM_FLAGS}
export MCTOLL=${LLPATH}/llvm-mctoll --compilation-db-path=/Users/martin/Developer/tum/ss21/bsc/benchmarks/ --output-format=ll --include-files="$(MCTOLL_INCLUDE)"

export CFLAGS=-lm -pthread
export INCLUDE_DIR=/Users/martin/Developer/tum/ss21/bsc/benchmarks/x86-sysroot/usr/include
