LLPATH=/root/llvm-project/build/bin

XCOMPILE_X86_FLAGS=-fuse-ld=${LLPATH}/ld.lld
XCOMPILE_ARM_FLAGS=--target=aarch64-linux-gnu --sysroot=$(AARCH_SYSROOT) -fuse-ld=${LLPATH}/ld.lld

MCTOLL_INCLUDE=/root/llvm-project/build/lib/clang/14.0.0/include/stddef.h,${INCLUDE_DIR}/stdio.h,${INCLUDE_DIR}/stdlib.h,${INCLUDE_DIR}/string.h,${INCLUDE_DIR}/strings.h,${INCLUDE_DIR}/pthread.h,${INCLUDE_DIR}/unistd.h,${INCLUDE_DIR}/time.h,${INCLUDE_DIR}/stdint.h,${INCLUDE_DIR}/x86_64-linux-gnu/sys/stat.h,${INCLUDE_DIR}/fcntl.h,${INCLUDE_DIR}/x86_64-linux-gnu/sys/mman.h,${INCLUDE_DIR}/sched.h,${INCLUDE_DIR}/ctype.h,${INCLUDE_DIR}/math.h,${INCLUDE_DIR}/arpa/inet.h,/root/benchmarks/include/missing_functions.h

export CC=${LLPATH}/clang ${XCOMPILE_X86_FLAGS}
export CC_ARM=${LLPATH}/clang ${XCOMPILE_ARM_FLAGS}
export MCTOLL=${LLPATH}/llvm-mctoll --output-format=ll --include-files=/usr/include/x86_64-linux-gnu/sys/time.h,/usr/include/assert.h,"$(MCTOLL_INCLUDE)"

export CFLAGS=-lm -pthread
export INCLUDE_DIR=/usr/include
